name: nicare
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  chewie: ^1.8.3
  video_player: ^2.9.1
  persistent_bottom_nav_bar: ^6.2.1
  speech_to_text: ^7.0.0
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.2
  local_auth: ^2.3.0
  appinio_video_player: ^1.2.2
  flutter_email_sender: ^6.0.3
  http: ^1.2.2
  awesome_snackbar_content: ^0.1.4
  video_thumbnail: ^0.5.3
  flutter_localizations:
    sdk: flutter
  intl: any
  lottie: ^3.2.0
  image_picker: ^1.1.2
  path_provider: ^2.0.12
  auto_size_text: ^3.0.0
  url_launcher: ^6.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/careAssist.png"
  remove_alpha_ios: true

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/united-states.png
    - assets/germany.png
    - assets/spain.png
    - assets/china.png
    - assets/japan.png
    - assets/Nokia-logonew.png
    - assets/animated/animated-tick.json
    - assets/animated/likeHeart.json  # Added this asset for the like animation
    - assets/sample_profile/profile1.jpg
    - assets/sample_profile/profile2.jpg
    - assets/sample_profile/profile3.jpg
    - assets/poster3.jpeg
    - assets/poster4.jpeg
    - assets/poster5.jpeg
    - assets/poster6.jpeg
    - assets/poster7.jpeg

  fonts:
    - family: NokiaPureHeadline
      fonts:
        - asset: assets/fonts/NokiaPureHeadline_Bd.ttf
        - asset: assets/fonts/NokiaPureHeadline_Rg.ttf
        - asset: assets/fonts/NokiaPureHeadline_Lt.ttf
        - asset: assets/fonts/NokiaPureHeadline_ULt.ttf